name: Build and Push Container Image
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'


jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set variables
        run: |
          echo SHORT_COMMIT_HASH=$(git rev-parse --short HEAD) > $GITHUB_ENV
          echo REPOSITORY=${{ format('{0}/{1}', steps.login-ecr.outputs.registry, 'abc-gestion-evaluaciones') }} >> $GITHUB_ENV
          echo IMAGE=$REPOSITORY:$SHORT_COMMIT_HASH >> $GITHUB_ENV
          echo IMAGE_LATEST=$REPOSITORY:latest >> $GITHUB_ENV
          echo "All variables:"
          echo $SHORT_COMMIT_HASH $REPOSITORY $IMAGE $IMAGE_LATEST


      - name: Build and push gestion-evaluaciones
        uses: docker/build-push-action@v5
        with:
          context: services/gestion-evaluaciones
          push: true
          tags: ${{ env.IMAGE }}, ${{ env.IMAGE_LATEST }} }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: services/gestion-evaluaciones/task-definition.json
          container-name: gestion-evaluaciones
          image: ${{ env.IMAGE }}
