name: Playwright Tests
on:
  push:
    branches:
      - 'master'
      - '*'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::428011609647:role/github-actions-alpaca-role
        aws-region: us-east-1
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      working-directory: test
      run: npm ci

    - name: Install Playwright Browsers
      working-directory: test
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      working-directory: test
      run: npx playwright test

    - name: Upload Playwright Report
      working-directory: test
      run: aws s3 sync --delete playwright-report s3://abc-jobs-artifacts/test_reports/functional_web
