# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Build, test and deploy Gestión Evaluaciones
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - 'services/gestion-evaluaciones/**'
  pull_request:
    branches:
      - 'master'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Set variables
        run: |
          SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
          REPOSITORY=${{ format('{0}/{1}', steps.login-ecr.outputs.registry, 'abc-gestion-evaluaciones') }}
          IMAGE=$REPOSITORY:$SHORT_COMMIT_HASH
          IMAGE_LATEST=$REPOSITORY:latest
          # Now set the varialbes for the next job steps
          echo "SHORT_COMMIT_HASH=$SHORT_COMMIT_HASH" >> $GITHUB_ENV
          echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "IMAGE_LATEST=$IMAGE_LATEST" >> $GITHUB_ENV
          # Debugging
          echo "Set the variables short $SHORT_COMMIT_HASH, repo $REPOSITORY, image $IMAGE, image latest $IMAGE_LATEST"

      - name: Build and push gestion-evaluaciones
        uses: docker/build-push-action@v5
        with:
          context: services/gestion-evaluaciones
          push: true
          tags: ${{ env.IMAGE }}, ${{ env.IMAGE_LATEST }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Pruebas unitarias
        if: false
        run: |
          cd services/gestion-evaluaciones
          docker-compose up -d
          docker-compose exec gestion-evaluaciones pytest

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: services/gestion-evaluaciones/task-definition.json
          container-name: gestion-evaluaciones
          image: ${{ env.IMAGE }}

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: gestion-evaluaciones
          cluster: abc-cluster
