# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Test report
on:
  push:
  workflow_call:
  workflow_run:
    workflows:
      - Gestión Evaluaciones
      - Gestión Empresas
      - Gestión Usuarios
      - Gestión Evaluaciones
    types:
      - completed
    # branches:
    #   - master


jobs:
  # Github pages
  build:
    runs-on: ubuntu-latest
    # concurrency: ci-${{ github.ref }}
    permissions:
      contents: write
      id-token: write
      pages: write

    steps:
      - name: Download reports from aws
        run: |
          aws s3 sync s3://abc-jobs-artifacts/test_reports _site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site

