# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Test report
on:
  workflow_call:
  push:
    paths:
      - 'others/test_report.html'
      - '.github/workflows/test_report.yaml'
  workflow_run:
    workflows:
      - Gestión Evaluaciones
      - Gestión Empresas
      - Gestión Usuarios
      - Gestión Evaluaciones
    types:
      - completed
    branches:
      - master
permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::428011609647:role/github-actions-alpaca-role

      - name: Download reports from aws
        run: |
          aws s3 sync s3://abc-jobs-artifacts/test_reports _site

      - name: Copy index.html
        run: |
          cp others/test_report.html _site/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
