# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Artifacts index
on:
  workflow_call:
  push:
    branches:
      - 'master'
    paths:
      - others/artifacts_index.html

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::428011609647:role/github-actions-alpaca-role

      - name: Upload artifacts index
        run: |
          # https://abc-jobs-artifacts.s3.amazonaws.com/index.html
          aws s3 cp others/artifacts_index.html s3://abc-jobs-artifacts/index.html
