# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Test report
on:
  workflow_call:
  workflow_run:
    workflows:
      - Gestión Evaluaciones
      - Gestión Empresas
      - Gestión Usuarios
      - Gestión Evaluaciones
    types:
      - completed
    # branches:
    #   - master


jobs:
  # Github pages
  build:
    runs-on: ubuntu-latest
    # concurrency: ci-${{ github.ref }}
    permissions:
      contents: write
      id-token: write
      pages: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: gestion_usuarios_cov_report
          path: _site/gestion_usuarios_cov_report

      - uses: actions/download-artifact@v3
        with:
          name: gestion_empresas_cov_report
          path: _site/gestion_empresas_cov_report

      - uses: actions/download-artifact@v3
        with:
          name: gestion_evaluaciones_cov_report
          path: _site/gestion_evaluaciones_cov_report

      - uses: actions/download-artifact@v3
        with:
          name: gestion_candidatos_cov_report
          path: _site/gestion_candidatos_cov_report

      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site

