# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Build, test and deploy Web app
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - 'web/**'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::428011609647:role/github-actions-alpaca-role
          aws-region: us-east-1

      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd web
          npm install

      - name: Test
        if: false
        run: |
          cd web
          nnpm run test

      - name: Build
        run: |
          cd web
          npm run build

      - name: Deploy to AWS S3
        run: |
          cd web
          aws s3 sync dist/ s3://abc-jobs-web --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1ZJZQZQZQZQZQ --paths "/*"
